name: Update GitHub Pages Docs

on:
  # 推送到main分支时触发
  push:
    branches:
      - main
    paths:
      - 'info.xlsx'
  
  # 允许手动触发
  workflow_dispatch:
  
  # 定时触发（可选，例如每天UTC时间0点）
  # schedule:
  #   - cron: '0 0 * * *'

# 设置权限
permissions:
  contents: write

jobs:
  update-docs:
    runs-on: ubuntu-latest
    
    steps:
      # 检出代码
      - name: Checkout repository
        uses: actions/checkout@v4
      
      # 设置Python环境
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'  # 根据需要修改版本
      
      # 安装依赖
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas openpyxl jinja2
      
      # 运行Python脚本生成文档
      - name: Run Python script
        run: |
          python scripts/update_docs.py
      
      # 提交更改到docs目录
      - name: Commit changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add docs/
          git diff --quiet && git diff --staged --quiet || git commit -m "Auto-update docs [skip ci]"
      
      # 推送更改
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

      # 部署到GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: gh-pages  # Pages分支
